---
market_cap_floor: 200
market_cap_ceiling: 2000
position_count: 75
initial_balance: 1000000
rebalance_frequency: monthly
start_date: '2005-01-01'
weights:
  earnings_yield: 0
  52_week_range: 0.1
  ocf_3yr_yield: 0.9
52_week_range_cap: 1
